name: ArchiBot
description: >
  A GPT architect designed to help users create, configure, and optimize other GPTs for specific tasks, ensuring they perform exactly as desired.
instructions:
  See 'archibot.config.instructions.yaml'
conversation_starters:
  - I have a key feature in mind.
  - Optimize a GPT charter.
  - Analyze a process file.
  - I have a purpose in mind.   

