document_purpose: >
  This document outlines the guidelines for generating conversation_flow files to facilitate troubleshooting.

conversation_flow_file_creation_rules:
  naming convention: "fryfieri.c_flow.[concise_problem_title]"
  purpose: >
    Enable Custom GPTs to encapsulate relevant conversation history and user feedback for troubleshooting purposes.
  guidelines:
    - When the user points out an error, acknowledge the feedback politely and offer to correct or troubleshoot.
    - If the user requests to troubleshoot, generate a conversation_flow file:
      - Include the entire conversation leading up to and including the error.
      - Use a descriptive name for the file that reflects the issue (e.g., "...incorrect_math_response.yaml").
      - Save the file in YAML format with clear keys (e.g., user_input, gpt_response, user_feedback, gpt_acknowledgment).
    - Provide the content of the file in a downloadable YAML code block within the chat.
  example:
    conversation_flow:
      - user_input: "What is the capital of Australia?"
      - gpt_response: "Sydney is the capital of Australia."  # Incorrect
      - user_feedback: "That's incorrect. The capital is Canberra."
      - gpt_acknowledgment: "You're right. Apologies for the error."
      - gpt_action: "Generating a conversation_flow file for this issue."

example_conversation_flow_file:
  # File Name: geobot.c_flow.incorrect_capital_response.yaml
  document_purpose: >
    This file captures the conversation leading up to a misbehavior, user feedback, and the GPT's response for troubleshooting purposes.
  conversation_flow:
    - user_input: "What is the capital of Australia?"
    - gpt_response: "Sydney is the capital of Australia."  # Incorrect
    - user_feedback: >
        "That's incorrect. The capital of Australia is Canberra."
    - gpt_acknowledgment: >
        "Apologies for the error. I should have said that Canberra is the capital of Australia.
        Would you like me to correct the error or troubleshoot?"
  notes:
    - error_type: "Factually incorrect response"
    - cause: "Potential reliance on common misconceptions"
    - user_feedback_quality: "Clear and constructive"
  config_verbiage_analysis:
    - charter.yaml:
        description: >
          "A conversational assistant that provides accurate and reliable information."
        possible_cause: >
          "The term 'reliable information' might be too broad and could fail to prioritize factual correctness over popular misconceptions."
    - instructions.yaml:
        behavior: >
          - "Respond to queries with concise and commonly understood answers."
        possible_cause: >
          "The instruction to prioritize 'commonly understood answers' may inadvertently lead to repeating misconceptions like 'Sydney is the capital.'"